// This acts as a global wrapper to every page generated by Next.js
// See https://nextjs.org/docs/advanced-features/custom-app

export default function ProjectLumiere({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page);

  return getLayout(<Component {...pageProps} />);
}
