// pages/_app.js acts as a global wrapper to every page generated by Next.js
// See https://nextjs.org/docs/advanced-features/custom-app

import '@styles/global.css';
import { ThemeProvider } from 'next-themes';

export default function ProjectLumiere({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page);

  return getLayout(
    <ThemeProvider attribute='class'>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}
