// pages/index.js maps to projectlumiere.org/ (our homepage)
// See https://nextjs.org/docs/routing/introduction#index-routes

import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useTheme } from 'next-themes';
import Layout from '@components/layouts/Layout';
import { Gradient } from '@lib/gradient';

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    setMounted(true);
    const gradient = new Gradient();
    gradient.initGradient('.gradient-canvas');
  }, []);

  return (
    <div>
      <Head>
        <title>Project Lumiere</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className=''>
        <canvas
          className='gradient-canvas'
          data-js-darken-top
          data-transition-in
        ></canvas>
      </div>

      <h1 className='text-6xl font-extrabold text-purple-500 dark:text-blue-500'>
        Bruh
      </h1>

      {mounted && (
        <button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>
          Change theme
        </button>
      )}
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
